### ISSUE TITLE
SCORE  coin

### ISSUE THREAD

**Issue by aieha** [MinseokOh/MNCommander#1]
SCORE coin

Recently swapped(POW to POS) and It is expected to grow.
The number of masternodes has increased a lot in recent months.(now 155 masternodes)

twitter account is active
https://twitter.com/scorecoinmark

[Specification]

ROI (annual): | 117.69% / 310 days
Paid rewards for masternodes: | 12,495.0001 SCORE
AVG masternode reward frequency: | 6h 15m 8s
Masternodes total: | 155
Supply: | 41,562,822 SCORE
Coins locked: | 3,875,000 SCORE (9.32%)
Required coins for masternode: | 25,000 SCORE
Masternode worth: | $1,790.23 / 0.11750 BTC

linux guide mady by user
  https://mega.nz/#!Fvxy3awI!aSDgWovx9tWuUBr6FLhUwTj4hZQQp6X6qAGkdJQyExM

window guide made by user
https://mega.nz/#!guITxY4D!LLqLh1YIawhOHeGI0IHWNUSTVAa6_e7dF5zyj9iz6OU

bitcointalk
https://bitcointalk.org/index.php?topic=2637706.0

**Comment by MinseokOh** [comment]
ok I'll comment again after work

Thx

**Comment by MinseokOh** [comment]
Score Added 

https://github.com/MinseokOh/score_qtbuild
